---

- name: Ensure base image is downloaded once
  ansible.builtin.get_url:
    url: "{{ base_image_url }}"
    dest: "{{ libvirt_vms_volume_path }}"
  when: not lookup('file', libvirt_vms_volume_path + '/' + base_image_name, errors='ignore') is defined

- name: Create Volumes
  import_tasks: ./volumes.yml

- name: Create VMs
  import_tasks: ./vms.yml

- name: Set Firewall
  import_tasks: ./set-firewall.yml