---

- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: true

- name: Add allow rules
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    zone: "{{ item.zone | default('public') }}"
    state: enabled
    permanent: true
    immediate: true
  when: item.action == 'allow' and item.port != 'all'
  loop: "{{ firewall_rules }}"
  loop_control:
    label: "{{ item.direction }} {{ item.action }} {{ item.port }}/{{ item.protocol }}"

- name: Add deny rich rules
  ansible.posix.firewalld:
    rich_rule: >-
      rule family="ipv4"
      direction="{{ item.direction }}"
      {% if item.port != 'all' %}
      protocol value="{{ item.protocol }}" port port="{{ item.port }}" protocol="{{ item.protocol }}"
      {% endif %}
      drop
    state: enabled
    zone: "{{ item.zone | default('public') }}"
    permanent: true
    immediate: true
  when: item.action == 'deny'
  loop: "{{ firewall_rules }}"
  loop_control:
    label: "{{ item.direction }} {{ item.action }} {{ item.port }}/{{ item.protocol }}"