# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative "./zones"

Vagrant.configure("2") do |config|
  role_nodes = Hash.new { |h, k| h[k] = [] }

  ZONES.each do |zone, zone_cfg|
    vlan = zone_cfg[:vlan]
    gateway = zone_cfg[:gateway]

    zone_cfg[:vms].each do |role, opts|
      (1..opts[:amount]).each do |i|
        hostname = "#{role}#{i}"

        role_nodes[role] << hostname

        config.vm.define hostname do |node|
          node.vm.box = "local/ubuntu-22.04.5"
          node.vm.hostname = hostname.gsub("_", "-")
          node.vm.disk :disk, size: opts[:disksize], primary: true
          node.vm.synced_folder '.', '/vagrant', disabled: true

          node.ssh.username = ""
          node.ssh.password = ""

          # Networks
          node.vm.network :public_network,
            :dev => vlan,
            :mode => "bridge",
            :type => "bridge",
            :ip => opts[:ips][i - 1],
            :subnet => "255.255.255.0",
            :gateway => gateway

          # Provider
          node.vm.provider :libvirt do |libvirt|
            libvirt.cpus = opts[:cpus]
            libvirt.memory = opts[:memory] * 1_024
          end
        end
      end
    end
  end

  openvpn = role_nodes
    .select { |k, _| k.include?("openvpn") }
    .values
    .flatten

  masters = role_nodes
    .select { |k, _| k.include?("master") }
    .values
    .flatten

  workers = role_nodes
    .select { |k, _| k.include?("worker") }
    .values
    .flatten

  primary_master_nodes = role_nodes
    .select { |k, _| k.include?("master") }
    .values
    .map { |nodes| nodes.sort.first }

  nodes = (masters + workers).uniq

  config.vm.provision "ansible", type: "ansible" do |ansible|
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.groups = {
      "openvpn" => openvpn,
      "primary_masters" => primary_master_nodes,
      "masters" => masters,
      "workers" => workers,
      "nodes" => nodes
    }
    ansible.extra_vars = {
      "primary_master" => primary_master_nodes
    }
  end
end