# -*- mode: ruby -*-
# vi: set ft=ruby :
# Virtual Machines
VM_LIST = {
  "zone_a" => {
    :ip => "10.10.0.10",
    :cpus => 6,
    :memory => 6_144,
    :disksize => "150GB"
  },
  "zone_b" => {
    :ip => "10.20.0.10",
    :cpus => 8,
    :memory => 18_432,
    :disksize => "200GB"
  },
  "zone_c" => {
    :ip => "172.16.0.10",
    :cpus => 6,
    :memory => 6_144,
    :disksize => "150GB"
  },
}

Vagrant.configure("2") do |config|
  # Get Virtual Machine names
  vm_names = VM_LIST.keys

  # Get IP list
  ips = VM_LIST.map { |_, config| config[:ip] }

  # Define groups
  group_hash = vm_names.each_with_object({}) do |hostname, hash|
    hash["group_#{hostname}"] = [hostname]
  end
  group_hash["all:children"] = vm_names

  # Define Virtual Machines
  VM_LIST.each do |hostname, opts|
    config.vm.define hostname do |node|
      # Default box disk size: 64GB
      node.vm.box = "bento/rockylinux-8.10"
      node.vm.hostname = hostname
      node.vm.network :private_network, ip: opts[:ip]
      node.vm.disk :disk, size: opts[:disksize], primary: true
      node.vm.synced_folder '.', '/vagrant', disabled: true

      node.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.cpus = opts[:cpus]
        vbox.memory = opts[:memory]
      end
    end
  end

  # Install prerequisites
  config.vm.provision "shell", path: "../provisioning/shell/prerequisites.sh"
  
  # Run playbook
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provisioning/playbooks/playbook.yml"
    ansible.groups = group_hash
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
    ansible.compatibility_mode = "2.0"
  end
end