---

- name: Create Jenkins namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ jenkins_name }}"

- name: Deploy Jenkins Deployment from template
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins/deployment.yaml.j2') | from_yaml }}"

- name: Deploy Jenkins Service from template
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'jenkins/service.yaml.j2') | from_yaml }}"